# This workflow runs your tests and ensures the directory for test results exists.

name: CI Workflow

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # This is the crucial step that creates the 'test' directory.
      # The '-p' flag ensures that no error is thrown if the directory already exists.
      - name: Create test results directory
        run: mkdir -p test

      - name: Install dependencies
        run: |
          npm install
          # Or your project's specific dependency installation command

      - name: Run tests
        # This command runs your test suite.
        # It is assumed your test runner is configured to output a 'results.xml' file in the 'test/' directory.
        run: npm test

      # Optional step to upload test results for analysis
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test/results.xml

